#!/bin/sh

set -eu

dist=$1
arch=$2

basetgz=/var/cache/pbuilder/debuilder-env.$dist.$arch.tgz

[ -f "$basetgz" ] && exit 0

pbuilder --create --basetgz "$basetgz" --architecture "$arch" --distribution "$dist"
