#!/bin/sh

. /etc/debuilder/config

for dist in $dists; do
    tmpdir="/var/tmp/debuilder/$dist"
    mkdir -p "$tmpdir"
    inoticoming --logfile "$tmpdir/inoticoming.log" \
        --pid-file "$tmpdir/inoticoming.pid" \
        "$spooldir/$dist" \
        --chdir "$spooldir/$dist" \
        --suffix .dsc \
        --stderr-to-log \
        debuilder-add-rebuildd-job {} "$dist" \;
done
