#!/bin/sh

set -eu

. debuilder-get-install-paths

. "$DEBUILDER_CONFDIR/config"

dsc=$1

if [ $# -ne 2 ]; then
    dstdir=$DEBUILDER_SPOOLDIR
else
    dstdir=$2
fi

dscdir=$(dirname "$dsc")

sed -n -e '
/^Files:/{
        :loop
        n
        /^$/ q
        s/^ //p
        b loop
}' "$dsc" | while read md5 _ filename; do
    filepath=$dscdir/$filename
    echo "$md5  $filepath" | md5sum --check --quiet
    cp --archive --target-directory="$dstdir" "$filepath"
done

cp --archive --target-directory="$dstdir" "$dsc"
